### ISSUE TITLE
v0.2.1 consistification

### ISSUE THREAD

**Issue by tmcw** [calvinmetcalf/geojson-assert#1]
Changed geojsonhint in v0.2.1 to always return an array of objects with message and line members, even when it's a JSON parse error. This means you should be able to rm some code here.

**Comment by calvinmetcalf** [comment]
so I can remove [the conditionals](https://github.com/calvinmetcalf/geojson-assert/blob/master/index.js#L7-L12) which check that it has those?

**Comment by tmcw** [comment]
Yep.
